buildwebsite:
    stage: build
    script:
        - cd src
        - bundle install
        - bundle exec jekyll build -d public
    # cache jekyll installation
    cache:
        paths:
            - vendor/
    artifacts:
        paths:
            - src/public